/* IXHUA's canonical clock, profile and validation primitives. No DOM. */
(function(root){'use strict';
const VERSION=10,DAY=86400000;
const clone=x=>JSON.parse(JSON.stringify(x));
function id(){if(root.crypto?.randomUUID)return root.crypto.randomUUID();if(root.REBUILD_RECORD_ID)return root.REBUILD_RECORD_ID();const a=new Uint8Array(16);if(!root.crypto?.getRandomValues)throw Error('Secure record identifiers are unavailable.');root.crypto.getRandomValues(a);a[6]=a[6]&15|64;a[8]=a[8]&63|128;return Array.from(a,(x,i)=>([4,6,8,10].includes(i)?'-':'')+x.toString(16).padStart(2,'0')).join('');}
function dateKey(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
function validDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s;}
function addDays(s,n){if(!validDate(s)||!Number.isInteger(n))throw Error('A valid calendar date is required.');return new Date(Date.parse(s+'T12:00:00Z')+n*DAY).toISOString().slice(0,10);}
function dow(s){return new Date(s+'T12:00:00Z').getUTCDay();}
function monday(s){return addDays(s,-((dow(s)+6)%7));}
function daysBetween(a,b){return Math.round((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/DAY);}
function parseDuration(input,{optional=false}={}){const s=String(input??'').trim();if(!s&&optional)return null;let seconds;if(/^\d{1,4}$/.test(s))seconds=Number(s)*60;else if(/^\d{1,4}[:.]\d{2}$/.test(s)){const [m,sec]=s.split(/[:.]/).map(Number);if(sec>59)throw Error('Seconds must be 00–59. Enter 9.15 for 9:15.');seconds=m*60+sec;}else if(/^\d{1,2}:\d{2}:\d{2}$/.test(s)){const [h,m,sec]=s.split(':').map(Number);if(m>59||sec>59)throw Error('Minutes and seconds must be 00–59.');seconds=h*3600+m*60+sec;}else throw Error('Enter minutes or minutes.seconds: 9.15 means 9:15.');if(seconds<=0||seconds>86400)throw Error('Enter a duration between one second and 24 hours.');return seconds;}
function duration(s){s=Math.max(0,Math.round(Number(s)||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0');}
function elapsed(s,now=Date.now()){return Math.max(0,s.elapsedMs||0)+(s.status==='active'?Math.max(0,now-s.resumedAt):0);}
function toggleClock(s,now=Date.now()){if(s.status==='active'){s.elapsedMs=elapsed(s,now);s.status='paused';s.resumedAt=null;}else if(s.status==='paused'){s.status='active';s.resumedAt=now;}else throw Error('Only an active session can be paused or resumed.');return s;}
function range(n,min,max,label){if(!Number.isFinite(n)||n<min||n>max)throw Error(label+' must be between '+min+' and '+max+'.');return n;}
function normalProfile(p={}){const running={goal:'first5k',experience:'new',days:3,currentDays:0,weeklyMinutes:0,continuousMinutes:0,consistentWeeks:0,benchmarkSeconds:null,benchmarkDistanceKm:1.609344,benchmarkDate:null,targetSeconds:null,goalDate:null,environment:'outdoor',longDay:0,longMinutes:60,preference:'variety',pain:false,...p.running};const strength={experience:'new',days:3,goal:'strength',split:'auto',currentDays:null,consistentWeeks:null,breakWeeks:0,pain:false,avoid:[],priorities:[],benchKg:null,squatKg:null,deadliftKg:null,targetBenchKg:null,...p.strength};const conditioning={enabled:false,focus:'general',days:1,experience:'new',modality:'airbike',core:true,recoveryMobility:true,...p.conditioning};return {primary:null,secondary:[],hybridPriority:'equal',presentation:p.presentation||(p.primary==='longevity'?'simple':'details'),language:'en',units:'imperial',age:null,heightCm:null,weightKg:null,sex:null,days:[1,3,5],minutes:45,preferredTime:'08:00',splitSessions:false,equipment:['bodyweight'],startedOn:dateKey(),...p,running,strength,conditioning,plyo:{enabled:false,experience:'none',landing:'unknown',surface:'unknown',pain:false,...p.plyo},schedule:{wake:'06:00',bed:'22:00',bufferMinutes:30,workDemand:'light',...p.schedule},nutrition:{goal:'maintain',activity:'light',diet:'omnivore',allergies:[],dislikes:[],budget:'moderate',...p.nutrition},capability:{balance:null,chairStands:null,walkMinutes:null,needs:[],...p.capability}};}
function validateProfile(p){if(!['runner','strength','hybrid','general','longevity','custom'].includes(p.primary))throw Error('Choose your athlete priority.');if(!Array.isArray(p.days)||!p.days.length||new Set(p.days).size!==p.days.length||p.days.some(n=>!Number.isInteger(n)||n<0||n>6))throw Error('Choose one or more unique training days.');range(p.minutes,10,240,'Session minutes');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.preferredTime))throw Error('Choose a valid training time.');range(p.running.days,0,7,'Running days');range(p.running.weeklyMinutes,0,3000,'Weekly running minutes');range(p.running.continuousMinutes,0,600,'Continuous running minutes');range(p.running.consistentWeeks,0,1000,'Recent consistent weeks');range(p.running.longMinutes,10,240,'Long-run window');for(const [n,min,max,label] of [[p.strength.days,1,6,'Lifting days'],[p.running.currentDays,0,7,'Current running days'],[p.running.longDay,0,6,'Long-run day'],[p.schedule.bufferMinutes,0,120,'Transition buffer']])range(n,min,max,label);for(const n of [p.running.days,p.running.currentDays,p.running.longDay,p.strength.days])if(!Number.isInteger(n))throw Error('Training days must be whole numbers.');if(!['imperial','metric'].includes(p.units)||!['equal','running','strength'].includes(p.hybridPriority)||!['simple','details'].includes(p.presentation||'details'))throw Error('Invalid units, hybrid priority or presentation mode.');for(const x of [p.running.experience,p.strength.experience,p.conditioning.experience])if(!['new','some','experienced','advanced'].includes(x))throw Error('Choose a valid training experience.');range(p.conditioning.days,0,3,'Conditioning days');if(!Number.isInteger(p.conditioning.days))throw Error('Conditioning days must be a whole number.');if(!['general','combat','mma','grappling','striking'].includes(p.conditioning.focus))throw Error('Choose a valid conditioning focus.');if(!['airbike','bike','row','run'].includes(p.conditioning.modality))throw Error('Choose a valid conditioning modality.');if(!Array.isArray(p.equipment)||!p.equipment.length)throw Error('Select available equipment.');for(const [n,min,max,label]of [[p.age,18,100,'Age'],[p.heightCm,120,230,'Height'],[p.weightKg,30,320,'Weight'],[p.capability.balance,0,300,'Balance'],[p.capability.chairStands,0,60,'Chair stands'],[p.capability.walkMinutes,0,600,'Comfortable walking'],[p.running.customDistanceKm,0.1,200,'Custom distance'],[p.strength.currentDays,0,6,'Current lifting days'],[p.strength.consistentWeeks,0,1000,'Consistent lifting weeks'],[p.strength.breakWeeks,0,520,'Lifting break']])if(n!=null)range(n,min,max,label);if(p.running.benchmarkDate&&!validDate(p.running.benchmarkDate))throw Error('Choose a valid benchmark date.');if(p.running.goalDate&&!validDate(p.running.goalDate))throw Error('Choose a valid goal date.');for(const x of ['benchmarkSeconds','targetSeconds'])if(p.running[x]!=null)range(p.running[x],1,86400,'Running time');return p;}
function validatePlan(plan){if(!Array.isArray(plan))throw Error('Training plan must be a list.');const ids=new Set();for(const s of plan){if(!s.id||ids.has(s.id))throw Error('Every planned session needs a unique ID.');ids.add(s.id);if(!validDate(s.date))throw Error('Session date is invalid.');range(s.minutes,1,240,'Session duration');if(!['running','strength','cardio','mobility','plyo','capability'].includes(s.type))throw Error('Unknown session domain.');if(s.type==='running'){if(!Array.isArray(s.segments)||!s.segments.length||s.segments.some(x=>!Number.isInteger(x.seconds)||x.seconds<=0))throw Error('A run needs valid timed segments.');if(Math.abs(s.minutes*60-s.segments.reduce((a,x)=>a+x.seconds,0))>0.01)throw Error('Run duration must equal its timed prescription.');}}return plan;}
function sanitize(value,depth=0){if(depth>30)throw Error('Backup nesting is invalid.');if(value===null||typeof value==='boolean'||typeof value==='string')return value;if(typeof value==='number'){if(!Number.isFinite(value))throw Error('Non-finite data is invalid.');return value;}if(Array.isArray(value)){if(value.length>100000)throw Error('Backup is too large.');return value.map(x=>sanitize(x,depth+1));}if(typeof value==='object'){const out={};for(const [k,v] of Object.entries(value)){if(['__proto__','constructor','prototype'].includes(k))throw Error('Unsafe backup property.');out[k]=sanitize(v,depth+1);}return out;}throw Error('Unsupported data in backup.');}
function validateState(s){if(!s||typeof s!=='object'||!s.profile||!Array.isArray(s.sessions)||!s.foodLog||typeof s.foodLog!=='object')throw Error('The backup is missing required IXHUA records.');if(s.athlete)validateProfile(s.athlete);if(s.trainingPlan)validatePlan(s.trainingPlan);return s;}
function transaction(state,storage,key,fn){const next=clone(state);fn(next);validateState(next);const stored=storage.getItem(key);if(stored&&(JSON.parse(stored).revision||0)>(state.revision||0))throw Error('Another tab saved newer data. Reload before editing.');next.revision=(state.revision||0)+1;storage.setItem(key,JSON.stringify(next));Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,next);return state;}
const api={VERSION,DAY,clone,id,dateKey,validDate,addDays,dow,monday,daysBetween,parseDuration,duration,elapsed,toggleClock,range,normalProfile,validateProfile,validatePlan,sanitize,validateState,transaction};root.IXHUA_CORE=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
