/* REBUILD domain engine. No DOM, provider credentials, or fabricated user data. */
(function(root){
'use strict';
const specs=[
['Bench Press','horizontal push','Chest','barbell'],['DB Bench Press','horizontal push','Chest','dumbbells'],['Push-Up','horizontal push','Chest','bodyweight'],['Incline DB Press','incline push','Chest','dumbbells'],['Incline Barbell Press','incline push','Chest','barbell'],['Chest Fly','chest isolation','Chest','dumbbells'],['Cable Fly','chest isolation','Chest','cables'],
['1-Arm DB Row','horizontal pull','Back','dumbbells'],['Chest-Supported Row','horizontal pull','Back','dumbbells'],['Cable Row','horizontal pull','Back','cables'],['Barbell Row','horizontal pull','Back','barbell'],['Lat Pulldown','vertical pull','Back','cables'],['Pull-Up','vertical pull','Back','pullup bar'],['Band Pulldown','vertical pull','Back','bands'],
['Overhead Press','vertical push','Shoulders','barbell'],['DB Shoulder Press','vertical push','Shoulders','dumbbells'],['Pike Push-Up','vertical push','Shoulders','bodyweight'],['Lateral Raise','shoulder isolation','Shoulders','dumbbells'],['Cable Lateral Raise','shoulder isolation','Shoulders','cables'],['Rear Delt Raise','rear delt','Shoulders','dumbbells'],['Band Reverse Fly','rear delt','Shoulders','bands'],
['DB Curl','elbow flexion','Biceps','dumbbells'],['Hammer Curl','elbow flexion','Biceps','dumbbells'],['Cable Curl','elbow flexion','Biceps','cables'],['Triceps Pressdown','elbow extension','Triceps','cables'],['DB Overhead Extension','elbow extension','Triceps','dumbbells'],['Band Pressdown','elbow extension','Triceps','bands'],
['Squat','squat','Quads','barbell'],['Goblet Squat','squat','Quads','dumbbells'],['Bodyweight Squat','squat','Quads','bodyweight'],['Front Squat','squat','Quads','barbell'],['Leg Press','squat','Quads','machines'],['Bulgarian Split Squat','single leg','Quads','dumbbells'],['Reverse Lunge','single leg','Quads','bodyweight'],['Step-Up','single leg','Quads','dumbbells'],['Leg Extension','knee extension','Quads','machines'],
['Romanian Deadlift','hinge','Hamstrings','barbell'],['DB Romanian Deadlift','hinge','Hamstrings','dumbbells'],['Single-Leg Hip Hinge','hinge','Hamstrings','bodyweight'],['Deadlift','hinge','Hamstrings','barbell'],['Hamstring Curl','knee flexion','Hamstrings','machines'],['Sliding Leg Curl','knee flexion','Hamstrings','sliders'],['Hip Thrust','hip extension','Glutes','barbell'],['Glute Bridge','hip extension','Glutes','bodyweight'],['Standing Calf Raise','calf raise','Calves','bodyweight'],['Seated Calf Raise','calf raise','Calves','dumbbells'],['Plank','anti extension','Core','bodyweight'],['Dead Bug','anti extension','Core','bodyweight'],['Pallof Press','anti rotation','Core','cables'],['Band Pallof Press','anti rotation','Core','bands'],['Hanging Knee Raise','trunk flexion','Core','pullup bar'],['Crunch','trunk flexion','Core','bodyweight'],['Farmer Carry','carry','Core','dumbbells']];
const cues={
'horizontal push':['Set your shoulders and brace your trunk.','Lower with control, keeping wrists over elbows.','Press through a comfortable range without bouncing.'],
'incline push':['Use a low incline and plant your feet.','Lower with forearms vertical.','Press without shrugging or arching excessively.'],
'chest isolation':['Keep a soft, consistent elbow bend.','Open only as far as your shoulders comfortably allow.','Bring your arms together without swinging.'],
'horizontal pull':['Brace and keep your trunk still.','Drive elbows back without shrugging.','Control the reach on the way down.'],
'vertical pull':['Start with controlled shoulders and a tall chest.','Pull elbows toward your ribs.','Return with control; avoid swinging.'],
'vertical push':['Brace with ribs over pelvis.','Press overhead through a comfortable range.','Avoid leaning back to finish the rep.'],
'shoulder isolation':['Use light resistance and soft elbows.','Lift slightly forward of your sides.','Lower slowly without shrugging.'],
'rear delt':['Support or brace your torso.','Open your arms with soft elbows.','Keep shoulders away from ears.'],
'elbow flexion':['Keep elbows close and still.','Curl without swinging your hips.','Lower fully with control.'],
'elbow extension':['Keep upper arms stable.','Extend elbows without locking forcefully.','Control the return.'],
'squat':['Brace before descending.','Keep your whole foot planted and knees tracking toes.','Stand through a comfortable controlled depth.'],
'single leg':['Use a stable stance and support if needed.','Lower with front knee tracking the toes.','Drive through the working foot; complete both sides.'],
'knee extension':['Align the machine pivot with your knee.','Extend without kicking or locking forcefully.','Lower slowly.'],
'hinge':['Brace and soften your knees.','Push hips back while keeping resistance close.','Stand by extending hips; do not overarch.'],
'knee flexion':['Keep hips stable.','Bend knees through a controlled range.','Return slowly without jerking.'],
'hip extension':['Keep ribs down and feet planted.','Drive through heels to lift hips.','Finish with glutes, without arching your low back.'],
'calf raise':['Use support for balance.','Rise through the balls of your feet.','Pause and lower slowly through comfortable range.'],
'anti extension':['Stack ribs over pelvis.','Brace while breathing normally.','Stop the set before your low back arches.'],
'anti rotation':['Set a stable stance and brace.','Resist rotation as you extend your arms.','Return slowly; train both sides.'],
 'trunk flexion':['Move slowly without pulling your neck.','Curl with your abdomen rather than momentum.','Return under control.'],
'carry':['Stand tall with ribs down.','Walk with controlled steps.','Keep shoulders level and breathe.']};
const library=specs.map(([name,pattern,primary,equipment],i)=>({id:'ex-'+i,name,pattern,primary,equipment,difficulty:/Front Squat|Pull-Up|Deadlift|Pike/.test(name)?'experienced':'some',secondary:({Chest:'Triceps • Shoulders',Back:'Biceps • Shoulders',Quads:'Glutes • Core',Hamstrings:'Glutes • Core',Glutes:'Hamstrings • Core',Shoulders:'Triceps • Upper back',Core:'Trunk stabilizers'})[primary]||'Stabilizers',sets:/isolation|flexion|extension|calf|rear delt/.test(pattern)?'2 × 10–15':'3 × 8–12',rest:/squat|hinge|push|pull/.test(pattern)?'2:00':'1:00',cues:cues[pattern],mistakes:['Using momentum instead of control','Continuing when technique breaks down','Forcing a painful range'],video:'https://www.youtube.com/results?search_query='+encodeURIComponent(name+' technique'),loadType:equipment==='bodyweight'?'bodyweight':equipment==='dumbbells'?'per hand':'total',repRange:/isolation|flexion|extension|calf|rear delt/.test(pattern)?[10,15]:[8,12],media:null}));
const templates={'Upper Body A':['Bench Press','1-Arm DB Row','Overhead Press','Lat Pulldown','Lateral Raise','DB Curl','Triceps Pressdown'],'Lower Body':['Squat','Romanian Deadlift','Bulgarian Split Squat','Hamstring Curl','Standing Calf Raise','Plank'],'Full Body':['Goblet Squat','Incline DB Press','Chest-Supported Row','Romanian Deadlift','Lat Pulldown','Standing Calf Raise','Dead Bug']};
library.forEach(e=>{if(e.name==='Plank'){e.sets='3 × 30 sec';e.logHint='seconds';e.repRange=null;}if(e.name==='Farmer Carry'){e.sets='3 × 20 m';e.logHint='20 m';e.repRange=null;}});
function alternatives(e,equipment){return library.filter(x=>x.name!==e.name&&x.pattern===e.pattern&&(!equipment||equipment.includes(x.equipment))).sort((a,b)=>(a.difficulty==='experienced')-(b.difficulty==='experienced'));}
function select(name,profile={},options={}){const equipment=options.equipment||profile.availableEquipment;let exercises=templates[name].map(n=>library.find(e=>e.name===n));if(equipment)exercises=exercises.map(e=>equipment.includes(e.equipment)?e:alternatives(e,equipment)[0]).filter(Boolean);if(options.minutes&&options.minutes<45)exercises=exercises.slice(0,Math.max(3,Math.floor(options.minutes/6)));return {title:name,type:'strength',exercises:exercises.map(e=>({...e,sets:profile.experience==='new'||options.easy?e.sets.replace(/^\d+/,'2'):e.sets}))};}
function completed(e){return (e.sets||[]).filter(s=>s.done&&Number.isFinite(+s.weight)&&+s.weight>=0&&Number.isFinite(+s.reps)&&+s.reps>0);}
function stats(session){const sets=(session.exercises||[]).filter(e=>!e.kind&&!['Plank','Farmer Carry'].includes(e.name)).flatMap(completed);return {exercises:(session.exercises||[]).filter(e=>e.sets?.length&&e.sets.every(s=>s.done)).length,sets:(session.exercises||[]).flatMap(completed).length,reps:sets.reduce((a,s)=>a+(+s.reps),0),volume:sets.reduce((a,s)=>a+(+s.reps)*(+s.weight),0)};}
function progression(e,history){const past=history.filter(s=>s.status==='completed').flatMap(s=>(s.exercises||[]).filter(x=>x.name===e.name).map(x=>({...x,date:s.endedAt}))).sort((a,b)=>b.date-a.date);if(!past.length)return {weight:null,reason:'No completed session yet. Start light and leave 2–3 controlled reps in reserve.'};const last=past[0],ss=completed(last);if(!ss.length)return {weight:null,reason:'No completed working sets to compare.'};const weight=Math.max(...ss.map(s=>+s.weight)),range=e.repRange||[8,12],all=ss.length===last.sets.length;const success=all&&ss.every(s=>+s.reps>=range[1]&&+s.weight===weight);const missed=ss.some(s=>+s.reps<range[0])||!all;return {weight:success&&weight>0?weight+(e.loadType==='per hand'?2.5:5):weight,reason:success?'You completed every set at the top of the rep range. Try the smallest available increase.':missed?'Keep the load; some sets were incomplete or below the rep target. Reduce it if technique or effort calls for it.':'Keep the load and build toward the top of your rep range.'};}
function records(session,history){const prs=[];for(const e of session.exercises||[]){const ss=completed(e).filter(s=>+s.weight>0);if(!ss.length)continue;const old=history.flatMap(x=>x.exercises||[]).filter(x=>x.name===e.name).flatMap(completed);if(!old.length)continue;const best=a=>Math.max(0,...a.map(s=>+s.weight));if(best(ss)>best(old))prs.push({exercise:e.name,type:'Weight PR',value:best(ss)});const rm=a=>Math.max(0,...a.filter(s=>+s.reps<=12).map(s=>+s.weight*(1+(+s.reps)/30)));if(rm(ss)>rm(old))prs.push({exercise:e.name,type:'Estimated 1RM PR',value:Math.round(rm(ss)*10)/10});for(const set of ss){const same=old.filter(x=>+x.weight===+set.weight);if(same.length&&+set.reps>Math.max(...same.map(x=>+x.reps))&&!prs.some(p=>p.exercise===e.name&&p.type==='Rep PR'))prs.push({exercise:e.name,type:'Rep PR',value:+set.reps,unit:'reps at '+set.weight+' lb'});}}const similar=history.filter(x=>x.type===session.type);if(['running','cardio'].includes(session.type)&&similar.length){const distance=+session.metrics?.distance||0,oldDistance=Math.max(0,...similar.map(x=>+x.metrics?.distance||0));if(distance>oldDistance)prs.push({exercise:session.title,type:'Distance PR',value:distance,unit:'mi'});if(session.elapsedMs>Math.max(...similar.map(x=>x.elapsedMs||0)))prs.push({exercise:session.title,type:'Duration PR',value:Math.round(session.elapsedMs/60000),unit:'min'});}return prs;}
function food(base,amount){if(!Number.isFinite(+amount)||+amount<=0)throw Error('Enter a positive serving amount.');const out={...base,servings:+amount};for(const k of ['cal','p','c','f']){if(base[k]===''||base[k]==null||!Number.isFinite(+base[k])||+base[k]<0)throw Error('Review all four nutrition fields.');out[k]=Math.round(+base[k]*amount*10)/10;}for(const k of ['fiber','sugar','sodium'])if(base[k]!==''&&base[k]!=null){if(!Number.isFinite(+base[k])||+base[k]<0)throw Error('Optional nutrients must be nonnegative.');out[k]=Math.round(+base[k]*amount*10)/10;}return out;}
function nutritionTarget(profile={}){const age=+profile.age,lb=+profile.bodyweight,cm=+profile.heightCm||(+profile.height*2.54),sex=profile.sex,activity=profile.activity||'moderate';if(!(age>=18&&age<=100&&lb>=70&&lb<=700&&cm>=120&&cm<=230)||!['male','female'].includes(sex))return null;const kg=lb/2.2046226218,sexTerm=sex==='male'?5:-161,rMR=10*kg+6.25*cm-5*age+sexTerm,factors={sedentary:1.2,light:1.375,moderate:1.55,high:1.725,veryHigh:1.9},factor=factors[activity]||1.55,maintenance=rMR*factor,goal=profile.goal||'general',goalFactor={fatloss:.85,muscle:1.07,hybrid:.97,run:1,general:1}[goal]||1,calories=Math.round(maintenance*goalFactor/10)*10,proteinPerKg={fatloss:2,muscle:1.8,hybrid:1.8,run:1.6,general:1.4}[goal]||1.6,protein=Math.round(kg*proteinPerKg),fat=Math.round(Math.max(kg*.7,calories*.25/9)),carbs=Math.max(130,Math.round((calories-protein*4-fat*9)/4));return {cal:calories,p:protein,c:carbs,f:fat,rMR:Math.round(rMR),maintenance:Math.round(maintenance/10)*10,method:'Mifflin–St Jeor estimate',activityFactor:factor,goalFactor,proteinPerKg,estimated:true};}
const api={library,templates,alternatives,select,completed,stats,progression,records,food,nutritionTarget};root.REBUILD_ENGINE=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
