(function(root){'use strict';const base=root.REBUILD_ENGINE||(typeof require!=='undefined'&&require('../engine.js'));
const muscles={pecClavicular:'Upper chest',pecSternal:'Chest',deltoidAnterior:'Front deltoid',deltoidMiddle:'Side deltoid',deltoidPosterior:'Rear deltoid',triceps:'Triceps',biceps:'Biceps',brachialis:'Brachialis',brachioradialis:'Brachioradialis',latissimus:'Latissimus dorsi',trapeziusUpper:'Upper trapezius',trapeziusMiddle:'Middle trapezius',trapeziusLower:'Lower trapezius',rhomboids:'Rhomboids',serratus:'Serratus anterior',rotatorCuff:'Rotator cuff',rectusAbdominis:'Rectus abdominis',obliques:'Obliques',erectorSpinae:'Spinal erectors',gluteMax:'Gluteus maximus',gluteMed:'Gluteus medius',rectusFemoris:'Rectus femoris',vastusLateralis:'Vastus lateralis',vastusMedialis:'Vastus medialis',bicepsFemoris:'Biceps femoris',semitendinosus:'Semitendinosus',semimembranosus:'Semimembranosus',adductors:'Hip adductors',iliopsoas:'Hip flexors',gastrocnemius:'Gastrocnemius',soleus:'Soleus',tibialisAnterior:'Tibialis anterior',forearmFlexors:'Forearm flexors'};
const q=['rectusFemoris','vastusLateralis','vastusMedialis'],h=['bicepsFemoris','semitendinosus','semimembranosus'];
const mappings=[
[['pecSternal'],['pecClavicular','deltoidAnterior','triceps']], [['pecSternal'],['pecClavicular','deltoidAnterior','triceps']], [['pecSternal'],['triceps','serratus','rectusAbdominis']], [['pecClavicular'],['pecSternal','deltoidAnterior','triceps']], [['pecClavicular'],['pecSternal','deltoidAnterior','triceps']], [['pecSternal'],['pecClavicular','deltoidAnterior']], [['pecSternal'],['pecClavicular','deltoidAnterior']],
[['latissimus'],['rhomboids','trapeziusMiddle','biceps','deltoidPosterior']], [['trapeziusMiddle','rhomboids'],['latissimus','biceps','deltoidPosterior']], [['latissimus','trapeziusMiddle'],['rhomboids','biceps','deltoidPosterior']], [['latissimus','trapeziusMiddle'],['rhomboids','biceps','erectorSpinae']], [['latissimus'],['biceps','trapeziusLower','brachialis']], [['latissimus'],['biceps','brachialis','rectusAbdominis']], [['latissimus'],['biceps','trapeziusLower']],
[['deltoidAnterior','deltoidMiddle'],['triceps','trapeziusUpper','serratus']], [['deltoidAnterior','deltoidMiddle'],['triceps','trapeziusUpper']], [['deltoidAnterior'],['triceps','serratus']], [['deltoidMiddle'],['trapeziusUpper']], [['deltoidMiddle'],['trapeziusUpper']], [['deltoidPosterior'],['trapeziusMiddle','rhomboids']], [['deltoidPosterior'],['rhomboids','trapeziusMiddle']],
[['biceps'],['brachialis','brachioradialis']], [['brachialis','brachioradialis'],['biceps']], [['biceps'],['brachialis']], [['triceps'],[]], [['triceps'],['serratus']], [['triceps'],[]],
[q,['gluteMax','adductors','erectorSpinae']], [q,['gluteMax','rectusAbdominis']], [q,['gluteMax','gluteMed']], [q,['gluteMax','erectorSpinae','rectusAbdominis']], [q,['gluteMax']], [q,['gluteMax','gluteMed','adductors']], [['gluteMax',...q],['gluteMed',...h]], [['gluteMax',...q],['gluteMed','gastrocnemius']], [q,[]],
[h,['gluteMax','erectorSpinae','forearmFlexors']], [h,['gluteMax','erectorSpinae']], [h,['gluteMax','gluteMed','erectorSpinae']], [['gluteMax',...h],q.concat(['erectorSpinae','latissimus','forearmFlexors'])], [h,['gastrocnemius']], [h,['gluteMax','gastrocnemius']], [['gluteMax'],h.concat(['adductors'])], [['gluteMax'],h], [['gastrocnemius'],['soleus']], [['soleus'],['gastrocnemius']], [['rectusAbdominis','obliques'],['serratus','gluteMax']], [['rectusAbdominis'],['obliques','iliopsoas']], [['obliques'],['rectusAbdominis','gluteMed']], [['obliques'],['rectusAbdominis','gluteMed']], [['rectusAbdominis','iliopsoas'],['obliques','forearmFlexors']], [['rectusAbdominis'],['obliques']], [['forearmFlexors','trapeziusUpper'],['obliques','gluteMed']]
];
const library=base.library.map((e,i)=>({...e,primaryMuscles:mappings[i][0],secondaryMuscles:mappings[i][1],type:'strength',measure:e.name==='Plank'?'seconds':e.name==='Farmer Carry'?'meters':'reps',loadType:/Goblet|Overhead Extension/.test(e.name)?'total':e.loadType,unilateral:/1-Arm|Single-Leg|Bulgarian|Step-Up|Lunge/.test(e.name),restSeconds:Number(e.rest.split(':')[0])*60+Number(e.rest.split(':')[1]),mediaRecipe:e.name}));
const extras=[
['Close-Grip Push-Up','horizontal push','Triceps',['triceps'],['pecSternal','deltoidAnterior'],'strength','reps',['Set hands a little narrower than shoulder width.','Keep a straight trunk and elbows close.','Lower and press without flaring the elbows.']],
['Side Plank','anti lateral flexion','Core',['obliques'],['gluteMed','serratus'],'strength','seconds',['Place elbow under shoulder.','Raise hips with ribs and pelvis aligned.','Keep breathing; use bent knees if needed.']],
['Ankle Rocks','ankle mobility','Calves',['soleus'],['gastrocnemius','tibialisAnterior'],'mobility','reps',['Face a wall with your heel down.','Guide knee over the middle toes.','Move slowly within a comfortable range.']],
['90/90 Hip Switch','hip mobility','Hips',['gluteMed'],['adductors','iliopsoas'],'mobility','reps',['Sit with knees bent and feet apart.','Rotate both knees from one side to the other.','Use hands for support without forcing range.']],
['Thoracic Rotation','thoracic mobility','Back',['obliques'],['erectorSpinae','rhomboids'],'mobility','reps',['Start on hands and knees.','Place one hand lightly beside your head.','Rotate through the upper back while hips stay still.']],
['Wall Slide','shoulder mobility','Shoulders',['serratus','trapeziusLower'],['deltoidAnterior','rotatorCuff'],'mobility','reps',['Stand with ribs stacked over pelvis.','Slide forearms upward through a comfortable range.','Do not arch your lower back to reach higher.']],
['Hip Flexor Rock','hip mobility','Hips',['iliopsoas'],['gluteMax','rectusAbdominis'],'mobility','seconds',['Kneel with one foot forward.','Gently tuck your pelvis and squeeze the rear glute.','Shift forward slightly; stop before discomfort.']],
['Snap Down','landing','Quads',q,['gluteMax','soleus'],'plyo','reps',['Rise tall onto the balls of your feet.','Drop quickly into a shallow athletic stance without jumping.','Hold a quiet, balanced landing for two seconds.']],
['Low Pogo','ankle rebound','Calves',['gastrocnemius','soleus'],['gluteMed','rectusAbdominis'],'plyo','reps',['Stand tall with soft knees.','Use small ankle-driven bounces.','Stop if contacts become loud or control is lost.']],
['Squat Jump','vertical jump','Quads',q.concat(['gluteMax']),['gastrocnemius','soleus'],'plyo','reps',['Begin in a shallow squat.','Jump upward with a controlled arm swing.','Land softly and reset fully before the next rep.']],
['Forward Hop and Stick','horizontal jump','Glutes',['gluteMax',...q],['gluteMed','gastrocnemius','soleus'],'plyo','reps',['Use a small forward jump.','Land on both feet with knees following toes.','Hold the landing before another repetition.']],
['Lateral Hop and Stick','lateral jump','Glutes',['gluteMed','gluteMax'],q.concat(['soleus']),'plyo','reps',['Hop a short distance sideways.','Absorb the landing with hip and knee.','Stabilize for two seconds; train both directions.']],
['Single-Leg Pogo','ankle rebound unilateral','Calves',['soleus','gastrocnemius'],['gluteMed','obliques'],'plyo','reps',['Balance on one foot.','Use very small rebounds and level hips.','Finish one side, rest, then repeat on the other.']],
['A-Skip','running drill','Hips',['iliopsoas','gastrocnemius'],['soleus','gluteMed','rectusAbdominis'],'plyo','reps',['March tall before adding a gentle skip.','Lift one knee while the opposite arm moves forward.','Place the foot under your hips; stay relaxed.']],
['Chair Stand','squat','Quads',q,['gluteMax','rectusAbdominis'],'capability','reps',['Use a stable chair against a wall.','Stand through your whole foot with control.','Sit softly; use arm support if needed.']],
['Supported Single-Leg Balance','balance','Glutes',['gluteMed'],['soleus','obliques'],'capability','seconds',['Stand beside stable support.','Lift one foot and maintain a level pelvis.','Use fingertip support as needed; practise both sides.']],
['Tandem Walk','balance','Glutes',['gluteMed'],['soleus','tibialisAnterior','obliques'],'capability','meters',['Walk beside a support surface.','Place one foot in front of the other at a comfortable distance.','Move slowly and look ahead.']],
['Supported Calf Raise','calf raise','Calves',['gastrocnemius'],['soleus'],'capability','reps',['Hold a stable support.','Rise evenly through the balls of your feet.','Lower slowly and keep balance.']],
['Prone W Raise','scapular control','Back',['trapeziusMiddle','rhomboids'],['rotatorCuff','deltoidPosterior'],'mobility','reps',['Lie face down with forehead supported.','Bend elbows into a W shape.','Gently lift arms without shrugging or arching.']],
['Lateral Lunge','single leg','Quads',q.concat(['adductors']),['gluteMax','gluteMed'],'strength','reps',['Step sideways and sit into that hip.','Keep the working knee aligned with toes.','Push back to the start and repeat both sides.']]
];
extras.forEach(([name,pattern,primary,pm,sm,type,measure,cues],i)=>library.push({id:'ix-'+i,name,pattern,primary,primaryMuscles:pm,secondaryMuscles:sm,secondary:sm.map(x=>muscles[x]).join(' · '),equipment:'bodyweight',difficulty:type==='plyo'?'some':'new',type,measure,cues,mistakes:['Rushing before control is established','Forcing a painful range','Continuing after technique deteriorates'],repRange:type==='plyo'?[3,8]:[8,12],restSeconds:type==='plyo'?90:45,rest:type==='plyo'?'1:30':'0:45',sets:type==='plyo'?'2 × 5':'2 × 8',loadType:'bodyweight',contactsPerRep:type==='plyo'?1:0,unilateral:/Single-Leg|Lateral Hop/.test(name),mediaRecipe:name}));
function get(idOrName){return library.find(e=>e.id===idOrName||e.name===idOrName);}
function alternatives(e,equipment){return library.filter(x=>x.id!==e.id&&x.type===e.type&&x.pattern===e.pattern&&equipment.includes(x.equipment));}
function validate(){const errors=[];for(const e of library){if(!e.primaryMuscles.length)errors.push(e.name+': no primary muscles');if(new Set([...e.primaryMuscles,...e.secondaryMuscles]).size!==e.primaryMuscles.length+e.secondaryMuscles.length)errors.push(e.name+': overlapping mapping');for(const m of [...e.primaryMuscles,...e.secondaryMuscles])if(!muscles[m])errors.push(e.name+': unknown '+m);if(e.cues.length<3)errors.push(e.name+': incomplete technique');}if(errors.length)throw Error(errors.join('\n'));return true;}
const api={library,muscles,get,alternatives,validate};root.IXHUA_EXERCISES=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
